import "~/styles/globals.css";
import { Inter as FontSans } from "next/font/google"

import { cn } from "../lib/utils"

export const metadata = {
  title: "Todo App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn(
      "min-h-screen bg-background font-sans antialiased",
      fontSans.variable
    )}>
      <body>{children}</body>
    </html>
  );
}
